# Generated by Django 2.0.1 on 2018-01-22 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='north_east',
            new_name='num_north',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='south_east',
            new_name='num_south',
        ),
    ]
